print("J")
print("i")
print("l")
print("l")
letter1='J'
letter2='i'
letter3='l'
print(letter1)
print(letter2)
print(letter3)
print(letter3)
letterx='l'
print(letter3)
print(letterx)
letterx='y'
print(letterx)
print(letter3)
letterx=letter1
print(letterx)
print(letter1)
letter1='z'
print(letterx)
print(letter1)